<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="6" total="15" passed="9">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="1423" started-at="2017-10-08T11:56:58Z" finished-at="2017-10-08T11:57:00Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="1423" started-at="2017-10-08T11:56:58Z" finished-at="2017-10-08T11:57:00Z">
      <class name="exe.Arthadb_Automation">
        <test-method status="PASS" signature="DB_Details()[pri:0, instance:exe.Arthadb_Automation@31a5c39e]" name="DB_Details" is-config="true" duration-ms="971" started-at="2017-10-08T17:26:58Z" finished-at="2017-10-08T17:26:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DB_Details -->
        <test-method status="PASS" signature="ArthaDB_ProdCodes_Check_TC001()[pri:0, instance:exe.Arthadb_Automation@31a5c39e]" name="ArthaDB_ProdCodes_Check_TC001" duration-ms="32" started-at="2017-10-08T17:26:59Z" finished-at="2017-10-08T17:26:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArthaDB_ProdCodes_Check_TC001 -->
        <test-method status="PASS" signature="ArthaDB_AuditDates_Check_TC002()[pri:0, instance:exe.Arthadb_Automation@31a5c39e]" name="ArthaDB_AuditDates_Check_TC002" duration-ms="16" started-at="2017-10-08T17:26:59Z" finished-at="2017-10-08T17:26:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArthaDB_AuditDates_Check_TC002 -->
        <test-method status="PASS" signature="DB_Details()[pri:0, instance:exe.Arthadb_Automation@31a5c39e]" name="DB_Details" is-config="true" duration-ms="0" started-at="2017-10-08T17:26:59Z" finished-at="2017-10-08T17:26:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DB_Details -->
        <test-method status="PASS" signature="DB_Details()[pri:0, instance:exe.Arthadb_Automation@31a5c39e]" name="DB_Details" is-config="true" duration-ms="31" started-at="2017-10-08T17:26:59Z" finished-at="2017-10-08T17:26:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DB_Details -->
        <test-method status="PASS" signature="ArthaDB_Account_Number_Check_TC003()[pri:0, instance:exe.Arthadb_Automation@31a5c39e]" name="ArthaDB_Account_Number_Check_TC003" duration-ms="0" started-at="2017-10-08T17:26:59Z" finished-at="2017-10-08T17:26:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArthaDB_Account_Number_Check_TC003 -->
        <test-method status="PASS" signature="DB_Details()[pri:0, instance:exe.Arthadb_Automation@31a5c39e]" name="DB_Details" is-config="true" duration-ms="15" started-at="2017-10-08T17:26:59Z" finished-at="2017-10-08T17:26:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DB_Details -->
        <test-method status="PASS" signature="ArthaDB_ChargeType_Check_TC004()[pri:0, instance:exe.Arthadb_Automation@31a5c39e]" name="ArthaDB_ChargeType_Check_TC004" duration-ms="0" started-at="2017-10-08T17:26:59Z" finished-at="2017-10-08T17:26:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArthaDB_ChargeType_Check_TC004 -->
        <test-method status="PASS" signature="DB_Details()[pri:0, instance:exe.Arthadb_Automation@31a5c39e]" name="DB_Details" is-config="true" duration-ms="32" started-at="2017-10-08T17:26:59Z" finished-at="2017-10-08T17:26:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DB_Details -->
        <test-method status="PASS" signature="ArthaDB_Invoice_Number_Check_TC005()[pri:0, instance:exe.Arthadb_Automation@31a5c39e]" name="ArthaDB_Invoice_Number_Check_TC005" duration-ms="0" started-at="2017-10-08T17:26:59Z" finished-at="2017-10-08T17:26:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArthaDB_Invoice_Number_Check_TC005 -->
        <test-method status="PASS" signature="DB_Details()[pri:0, instance:exe.Arthadb_Automation@31a5c39e]" name="DB_Details" is-config="true" duration-ms="16" started-at="2017-10-08T17:26:59Z" finished-at="2017-10-08T17:26:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DB_Details -->
        <test-method status="PASS" signature="ArthaDB_Transaction_Amount_Check_TC006()[pri:0, instance:exe.Arthadb_Automation@31a5c39e]" name="ArthaDB_Transaction_Amount_Check_TC006" duration-ms="15" started-at="2017-10-08T17:26:59Z" finished-at="2017-10-08T17:26:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArthaDB_Transaction_Amount_Check_TC006 -->
        <test-method status="PASS" signature="DB_Details()[pri:0, instance:exe.Arthadb_Automation@31a5c39e]" name="DB_Details" is-config="true" duration-ms="0" started-at="2017-10-08T17:26:59Z" finished-at="2017-10-08T17:26:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DB_Details -->
        <test-method status="FAIL" signature="ArthaDB_ChargeSign_Check_TC007()[pri:0, instance:exe.Arthadb_Automation@31a5c39e]" name="ArthaDB_ChargeSign_Check_TC007" duration-ms="16" started-at="2017-10-08T17:26:59Z" finished-at="2017-10-08T17:26:59Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[PAYMENTS-Charge Sign Codes check is Failed at Account_Number=ACCD101N8776123, expected:<0> but was:<1>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: PAYMENTS-Charge Sign Codes check is Failed at Account_Number=ACCD101N8776123, expected:<0> but was:<1>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.Arthadb_Automation.ArthaDB_ChargeSign_Check_TC007(Arthadb_Automation.java:300)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArthaDB_ChargeSign_Check_TC007 -->
        <test-method status="PASS" signature="DB_Details()[pri:0, instance:exe.Arthadb_Automation@31a5c39e]" name="DB_Details" is-config="true" duration-ms="16" started-at="2017-10-08T17:26:59Z" finished-at="2017-10-08T17:26:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DB_Details -->
        <test-method status="FAIL" signature="ArthaDB_Record_Type_Check_TC008()[pri:0, instance:exe.Arthadb_Automation@31a5c39e]" name="ArthaDB_Record_Type_Check_TC008" duration-ms="0" started-at="2017-10-08T17:26:59Z" finished-at="2017-10-08T17:26:59Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[PAYMENTS-Record Type check is Failed at Invoice_Number=J9908844423C102,J9160067066C122,J91606706e6C122, expected:<0> but was:<3>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: PAYMENTS-Record Type check is Failed at Invoice_Number=J9908844423C102,J9160067066C122,J91606706e6C122, expected:<0> but was:<3>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.Arthadb_Automation.ArthaDB_Record_Type_Check_TC008(Arthadb_Automation.java:336)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArthaDB_Record_Type_Check_TC008 -->
        <test-method status="FAIL" signature="ArthaDB_Customer_First_Last_Name_Check_TC009()[pri:0, instance:exe.Arthadb_Automation@31a5c39e]" name="ArthaDB_Customer_First_Last_Name_Check_TC009" duration-ms="16" started-at="2017-10-08T17:26:59Z" finished-at="2017-10-08T17:26:59Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[CUSTOMERS-First & Last Name check is Failed at SSN=123-4s5-6791,123-45-672, expected:<0> but was:<2>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: CUSTOMERS-First & Last Name check is Failed at SSN=123-4s5-6791,123-45-672, expected:<0> but was:<2>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.Arthadb_Automation.ArthaDB_Customer_First_Last_Name_Check_TC009(Arthadb_Automation.java:371)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArthaDB_Customer_First_Last_Name_Check_TC009 -->
        <test-method status="PASS" signature="DB_Details()[pri:0, instance:exe.Arthadb_Automation@31a5c39e]" name="DB_Details" is-config="true" duration-ms="0" started-at="2017-10-08T17:26:59Z" finished-at="2017-10-08T17:26:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DB_Details -->
        <test-method status="FAIL" signature="ArthaDB_Customers_SSN_Check_TC010()[pri:0, instance:exe.Arthadb_Automation@31a5c39e]" name="ArthaDB_Customers_SSN_Check_TC010" duration-ms="15" started-at="2017-10-08T17:26:59Z" finished-at="2017-10-08T17:26:59Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[CUSTOMERS- SSN check is Failed at CustomerPK=1,2,3,4,5,6, expected:<0> but was:<6>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: CUSTOMERS- SSN check is Failed at CustomerPK=1,2,3,4,5,6, expected:<0> but was:<6>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.Arthadb_Automation.ArthaDB_Customers_SSN_Check_TC010(Arthadb_Automation.java:407)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArthaDB_Customers_SSN_Check_TC010 -->
        <test-method status="PASS" signature="DB_Details()[pri:0, instance:exe.Arthadb_Automation@31a5c39e]" name="DB_Details" is-config="true" duration-ms="0" started-at="2017-10-08T17:26:59Z" finished-at="2017-10-08T17:26:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DB_Details -->
        <test-method status="PASS" signature="DB_Details()[pri:0, instance:exe.Arthadb_Automation@31a5c39e]" name="DB_Details" is-config="true" duration-ms="16" started-at="2017-10-08T17:26:59Z" finished-at="2017-10-08T17:26:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DB_Details -->
        <test-method status="PASS" signature="ArthaDB_Record_Type_Check_TC011()[pri:0, instance:exe.Arthadb_Automation@31a5c39e]" name="ArthaDB_Record_Type_Check_TC011" duration-ms="15" started-at="2017-10-08T17:26:59Z" finished-at="2017-10-08T17:26:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArthaDB_Record_Type_Check_TC011 -->
        <test-method status="PASS" signature="DB_Details()[pri:0, instance:exe.Arthadb_Automation@31a5c39e]" name="DB_Details" is-config="true" duration-ms="0" started-at="2017-10-08T17:26:59Z" finished-at="2017-10-08T17:26:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DB_Details -->
        <test-method status="PASS" signature="ArthaDB_Premise_City_Check_TC012()[pri:0, instance:exe.Arthadb_Automation@31a5c39e]" name="ArthaDB_Premise_City_Check_TC012" duration-ms="0" started-at="2017-10-08T17:26:59Z" finished-at="2017-10-08T17:26:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArthaDB_Premise_City_Check_TC012 -->
        <test-method status="PASS" signature="DB_Details()[pri:0, instance:exe.Arthadb_Automation@31a5c39e]" name="DB_Details" is-config="true" duration-ms="0" started-at="2017-10-08T17:26:59Z" finished-at="2017-10-08T17:26:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DB_Details -->
        <test-method status="PASS" signature="ArthaDB_PrimaryPhoneNumber_TC013()[pri:0, instance:exe.Arthadb_Automation@31a5c39e]" name="ArthaDB_PrimaryPhoneNumber_TC013" duration-ms="16" started-at="2017-10-08T17:26:59Z" finished-at="2017-10-08T17:27:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArthaDB_PrimaryPhoneNumber_TC013 -->
        <test-method status="PASS" signature="DB_Details()[pri:0, instance:exe.Arthadb_Automation@31a5c39e]" name="DB_Details" is-config="true" duration-ms="15" started-at="2017-10-08T17:27:00Z" finished-at="2017-10-08T17:27:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DB_Details -->
        <test-method status="FAIL" signature="ArthaDB_Customer_Details_Update_Check_TC014()[pri:0, instance:exe.Arthadb_Automation@31a5c39e]" name="ArthaDB_Customer_Details_Update_Check_TC014" duration-ms="16" started-at="2017-10-08T17:27:00Z" finished-at="2017-10-08T17:27:00Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[Customer - Details are updated at Customer SSN= 123-45-6792,123-45-6791,123-45-6790,123-45-6789,123-45-6794, expected:<0> but was:<5>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: Customer - Details are updated at Customer SSN= 123-45-6792,123-45-6791,123-45-6790,123-45-6789,123-45-6794, expected:<0> but was:<5>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.Arthadb_Automation.ArthaDB_Customer_Details_Update_Check_TC014(Arthadb_Automation.java:539)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArthaDB_Customer_Details_Update_Check_TC014 -->
        <test-method status="PASS" signature="DB_Details()[pri:0, instance:exe.Arthadb_Automation@31a5c39e]" name="DB_Details" is-config="true" duration-ms="16" started-at="2017-10-08T17:27:00Z" finished-at="2017-10-08T17:27:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DB_Details -->
        <test-method status="FAIL" signature="ArthaDB_Customer_Details_Insert_Check_TC015()[pri:0, instance:exe.Arthadb_Automation@31a5c39e]" name="ArthaDB_Customer_Details_Insert_Check_TC015" duration-ms="0" started-at="2017-10-08T17:27:00Z" finished-at="2017-10-08T17:27:00Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[Customer - Details are Inserted at Customer ID= 102, expected:<0> but was:<1>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: Customer - Details are Inserted at Customer ID= 102, expected:<0> but was:<1>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.Arthadb_Automation.ArthaDB_Customer_Details_Insert_Check_TC015(Arthadb_Automation.java:565)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArthaDB_Customer_Details_Insert_Check_TC015 -->
      </class> <!-- exe.Arthadb_Automation -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
